os:
  - linux

language: python

python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - make check
  - make test
  - make coverage

after_success:
  - coveralls
